---
deployment:
  tasks:
    - export DEPLOYPATH=/home/artreene/public_html/
    - export REPO=/home/artreene/repositories/ArTree
    - php $REPO/composer.phar install > $DEPLOYPATH/composer-log.txt
    - /bin/cp -R /home/artreene/repositories/ArTree/* $DEPLOYPATH > $DEPLOYPATH/copy-log1.txt
    - /bin/cp -R /home/artreene/public_html/public/css $DEPLOYPATH > $DEPLOYPATH/copy-log2.txt
    - /bin/cp -R /home/artreene/public_html/public/images $DEPLOYPATH > $DEPLOYPATH/copy-log3.txt
    - /bin/cp -R /home/artreene/public_html/public/js $DEPLOYPATH > $DEPLOYPATH/copy-log4.txt
    - /bin/cp -R /home/artreene/public_html/public/webfonts $DEPLOYPATH > $DEPLOYPATH/copy-log5.txt
    - php artisan migrate
    - php artisan db:seed
    - php artisan storage:link
