---
deployment:
  tasks:
    - export DEPLOYPATH=/home/artreene/public_html/
    - cp -R /home/artreene/repositories/ArTree/* $DEPLOYPATH
    - cp -R /home/artreene/public_html/public/* $DEPLOYPATH
    - php $DEPLOYPATH/composer.phar install
