---
deployment:
  tasks:
    - export DEPLOYPATH=/home/artreene/public_html/
    - export REPO=/home/artreene/repositories/ArTree
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php $REPO/composer.phar install > $DEPLOYPATH/composer-log.txt
    - /bin/cp -Rf /home/artreene/repositories/ArTree/ $DEPLOYPATH
    - /bin/cp -Rf /home/artreene/public_html/public/css $DEPLOYPATH
    - /bin/cp -Rf /home/artreene/public_html/public/images $DEPLOYPATH
    - /bin/cp -Rf /home/artreene/public_html/public/js $DEPLOYPATH
    - /bin/cp -Rf /home/artreene/public_html/public/webfonts $DEPLOYPATH
    - php artisan migrate
    - php artisan db:seed
    - php artisan storage:link
