---
deployment:
  tasks:
    - export DEPLOYPATH=/home/artreene/public_html/
    - export REPO=/home/artreene/repositories/ArTree
    - php $REPO/composer.phar install > $DEPLOYPATH/composer-log.txt
    - cp -R /home/artreene/repositories/ArTree/* $DEPLOYPATH
    - shopt -s extglob > $DEPLOYPATH/terminal-log.txt
    - cp !(index*) -R /home/artreene/public_html/public/* $DEPLOYPATH
