---
deployment:
  tasks:
    - export DEPLOYPATH=/home/artreene/public_html
    - export REPO=/home/artreene/repositories/ArTree
    - php $REPO/composer.phar install > $DEPLOYPATH/composer-log.txt
    - /bin/cp -R $REPO/* $DEPLOYPATH/
    - /bin/cp -R $DEPLOYPATH/public/css $DEPLOYPATH/
    - /bin/cp -R $DEPLOYPATH/images $DEPLOYPATH/
    - /bin/cp -R $DEPLOYPATH/js $DEPLOYPATH/
    - /bin/cp -R $DEPLOYPATH/webfonts $DEPLOYPATH/
